site_name: cookbooks
theme: material
copyright: Copyright &copy; 2022 Blockchain Technology Partners
extra_css: [extra.css]
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: index.md
#  - Chronicle:
#    - Overview: chronicle/index.md
#    - Domain1: chronicle/domain1.md
#    - Domain2: chronicle/domain2.md
  - Equinix Metal: equinix/index.md
  - SUSE Rancher: rancher/index.md
