---
site_name: cookbooks
site_url: https://docs.btp.works/cookbooks
theme: material
copyright: Copyright &copy; 2023 BTP
extra_css: [extra.css]
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - Chronicle:
      - SUSE Rancher: chronicle/rancher.md
  - Sextant:
      - Equinix Metal: sextant/equinix.md
      - SUSE Rancher: sextant/rancher.md
