site_name: cookbooks
site_url: https://docs.btp.works/cookbooks
theme: material
copyright: Copyright &copy; 2022 BTP
extra_css: [extra.css]
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - Equinix Metal: equinix/index.md
  - SUSE Rancher: rancher/index.md
